config/routes.rb
Instagram1::Application.routes.draw do
  resources :gettweets
  resources :users
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  

  root :to => 'gettweets#index'

end

app/models/gettweet.rb
class Gettweet < ActiveRecord::Base
  attr_accessible :category, :date, :store_id, :tags, :tweet, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :name, :provider, :uid

  def self.from_omniauth(auth)
  	#slice method returns a new hash with the keys specified /extracts one hash from another.
  	#attempt to find provider and userid in User table if not found create user from omnimauth auth hash.
    #SELECT provider, uid, name FROM Users WHERE provider = twitter AND uid = uid.
  	where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
  	#create a user from omniauth hash.
  	create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]    
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
   
  #make the method available to all of the controllers. 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  #make method available to view.
  helper_method :current_user

end

app/controllers/gettweets_controller.rb
class GettweetsController < ApplicationController
  # GET /gettweets
  # GET /gettweets.json
  def index
    @gettweets = Gettweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gettweets }
    end
  end

  # GET /gettweets/1
  # GET /gettweets/1.json
  def show
    @gettweet = Gettweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gettweet }
    end
  end

  # GET /gettweets/new
  # GET /gettweets/new.json
  def new
    @gettweet = Gettweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gettweet }
    end
  end

  # GET /gettweets/1/edit
  def edit
    @gettweet = Gettweet.find(params[:id])
  end

  # POST /gettweets
  # POST /gettweets.json
  def create
    @gettweet = Gettweet.new(params[:gettweet])

    respond_to do |format|
      if @gettweet.save
        format.html { redirect_to @gettweet, notice: 'Gettweet was successfully created.' }
        format.json { render json: @gettweet, status: :created, location: @gettweet }
      else
        format.html { render action: "new" }
        format.json { render json: @gettweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gettweets/1
  # PUT /gettweets/1.json
  def update
    @gettweet = Gettweet.find(params[:id])

    respond_to do |format|
      if @gettweet.update_attributes(params[:gettweet])
        format.html { redirect_to @gettweet, notice: 'Gettweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gettweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gettweets/1
  # DELETE /gettweets/1.json
  def destroy
    @gettweet = Gettweet.find(params[:id])
    @gettweet.destroy

    respond_to do |format|
      format.html { redirect_to gettweets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
	   #To view contents of omniauth auth hash
	   #raise env["omniauth.auth"].to_yaml

	   #User model "from_omniauth" method
	   user = User.from_omniauth(env["omniauth.auth"])
	   session[:user_id] = user.id 
	   #redirect_to root_url, notice: "Signed in!"
	   redirect_to gettweets_path, notice: "Signed in!"

	end

	def destroy
       session[:user_id] = nil
       redirect_to gettweets_path, notice: "Signed out!"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gettweets_helper.rb
module GettweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gettweets/_form.html.erb
<%= form_for @gettweet, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :tweet, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tweet, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :date, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :user_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :store_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :store_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tags, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                gettweets_path, :class => 'btn' %>
  </div>
<% end %>

app/views/gettweets/edit.html.erb
<%- model_class = Gettweet -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gettweets/index.html.erb
<%- model_class = Gettweet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:tweet) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @gettweets.each do |gettweet| %>
      <tr>
        <td><%= link_to gettweet.id, gettweet_path(gettweet) %></td>
        <td><%= gettweet.tweet %></td>
        <td><%= gettweet.category %></td>
        <td><%= gettweet.date %></td>
        <td><%= gettweet.user_id %></td>
        <td><%= gettweet.store_id %></td>
        <td><%= gettweet.tags %></td>
        <td><%=l gettweet.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_gettweet_path(gettweet), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      gettweet_path(gettweet),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_gettweet_path,
            :class => 'btn btn-primary' %>

app/views/gettweets/new.html.erb
<%- model_class = Gettweet -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gettweets/show.html.erb
<%- model_class = Gettweet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:tweet) %>:</strong></dt>
  <dd><%= @gettweet.tweet %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @gettweet.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @gettweet.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @gettweet.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:store_id) %>:</strong></dt>
  <dd><%= @gettweet.store_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
  <dd><%= @gettweet.tags %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              gettweets_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_gettweet_path(@gettweet), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              gettweet_path(@gettweet),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Streamgettr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
	   <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <a class="brand" href="#">Streamgettr</a>
       <!-- below are the collapsed button links -->
       <div class="nav-collapse">
           <ul class="nav nav-list">
             <li class="works_nav"><a href="#"><i class="icon-cog"></i>  How it works</a></li>
             <li class="settings_nav"><a href="#"><i class="icon-wrench"></i>  Settings</a></li>
           </ul> 
           <ul class="nav pull-right">
           <!-- sign in with twitter -->
           <%#<% if !current_user %> 
           <% unless current_user %> 
              <li class="twitter_nav"><%= link_to "Sign in with twitter", "/auth/twitter" %></li>
           <% end %>  
           <!-- login form--> 
           <% unless current_user %>
           <!--
           <form class="form-inline">
  				 <input type="text" class="input-small" placeholder="Email">
  				 <input type="password" class="input-small" placeholder="Password">
  				 <label class="checkbox">
    				<input type="checkbox"> Remember me
  				 </label>
  				 <button type="submit" class="btn btn-mini btn-primary">Sign in</button>
			     </form>-->
			     <% else %>
			       <div class="signin_nav">
                Signed is as <%= current_user.name %> |        
                <%= link_to "Sign out", signout_path %>
              </div>
			     <% end %>
           </ul>
        </div>        
     </div>   
   </div>
  </div>

<div class="container">
 <%= yield %>
</div>

</body>
</html>